# Generated by Django 6.0.6 on 2026-07-02 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalevaluation",
            name="main_doctor_name",
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="الطبيب المسؤول",
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="رقم التتبع التسلسلي",
            ),
        ),
    ]
