# Generated by Django 6.0.6 on 2026-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0003_patient_document_images_phone_rules_and_injury_degree"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommitteeDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="اسم الطبيب"
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="الاختصاص"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعّال")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإضافة"
                    ),
                ),
            ],
            options={
                "verbose_name": "طبيب لجنة",
                "verbose_name_plural": "أطباء اللجنة",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="children_count",
            field=models.PositiveIntegerField(default=0, verbose_name="عدد الأطفال"),
        ),
        migrations.AlterField(
            model_name="medicalevaluation",
            name="committee_members",
            field=models.TextField(
                blank=True, null=True, verbose_name="أسماء الأطباء الحاضرين والمعتمدين"
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="social_status",
            field=models.CharField(
                choices=[
                    ("single", "أعزب"),
                    ("married", "متزوج"),
                    ("divorced", "مطلق"),
                ],
                max_length=20,
                verbose_name="الوضع الاجتماعي",
            ),
        ),
        migrations.AddField(
            model_name="medicalevaluation",
            name="committee_doctors",
            field=models.ManyToManyField(
                blank=True,
                to="reception.committeedoctor",
                verbose_name="الأطباء الحاضرون والمعتمدون",
            ),
        ),
    ]
